/**
 * Sparse comment worker for simulated agents. It writes directly through the
 * unified comments table after resolving live parent rows, keeping volume low
 * and capped per persona.
 *
 * Comment text is generated by the LLM (server/agents/llmCommentGenerator.ts)
 * with full surface context. There is no template fallback — if generation
 * fails for an agent in a sweep, we skip them rather than post something
 * generic. Quality over quantity.
 */

import { and, count, desc, eq, gt, gte, inArray, sql } from "drizzle-orm";
import {
  agentConfigs,
  comments as unifiedComments,
  matchups,
  opinionPolls,
  opinionPollVotes,
  predictionMarkets,
  profiles,
  trendingPolls,
  trendingPollVotes,
  votes,
} from "@shared/schema";
import { db } from "../db";
import { log } from "../log";
import {
  getSimulationProfile,
  isV2SimulationProfile,
  type AgentSimulationProfile,
} from "./simulationProfile";
import { fetchCommentContext, findReplyTarget, type CommentSurface, type ReplyTarget } from "./commentContext";
import { generateAgentComment, type AgentForComment } from "./llmCommentGenerator";
import {
  castMatchupVoteForUser,
  castOpinionPollVoteForUser,
  castSentimentPollVoteForUser,
  countAgentVotesThisWeek,
} from "./voteWorker";

/**
 * Probability that an agent's daily comment becomes a reply to someone
 * else's existing comment instead of a fresh top-level post. Replies are
 * conversational glue — too many makes the site feel like a thread farm,
 * too few looks like everyone is shouting past each other. 30% feels
 * Polymarket-natural.
 */
const REPLY_PROBABILITY = 0.30;

/**
 * Defensive cap on how many comments a single sweep can post platform-wide.
 * With 56 agents × ~10% daily chance × weeklyCap=1, expected daily volume is
 * 3-6 comments. This ceiling exists so a misconfiguration can't quietly
 * generate hundreds.
 */
const MAX_COMMENTS_PER_SWEEP = 30;

const COMMENT_WORKER_BOOT_DELAY_MS = 7 * 60_000;

interface EligibleCommentParent {
  parentType: CommentSurface;
  parentId: string;
  title: string;
  category: string | null;
}

function getMondayOfWeek(): Date {
  const now = new Date();
  const day = now.getUTCDay();
  const diff = day === 0 ? 6 : day - 1;
  const monday = new Date(now);
  monday.setUTCDate(now.getUTCDate() - diff);
  monday.setUTCHours(0, 0, 0, 0);
  return monday;
}

async function countAgentCommentsThisWeek(userId: string): Promise<number> {
  const [row] = await db
    .select({ c: count() })
    .from(unifiedComments)
    .where(
      and(
        eq(unifiedComments.userId, userId),
        gte(unifiedComments.createdAt, getMondayOfWeek()),
        sql`${unifiedComments.deletedAt} IS NULL`,
      ),
    );
  return Number(row?.c ?? 0);
}

/** All currently-open parents across every commentable surface, with no
 *  per-user filtering. Reused by both the top-level path (which then
 *  excludes parents the agent has already commented on) and the reply
 *  path (which doesn't — replying to a thread you've already posted in
 *  is normal). */
async function getOpenParents(): Promise<EligibleCommentParent[]> {
  const now = new Date();
  // Limits raised from 30 → 200 per surface. The previous 30-newest cap
  // meant agents were structurally blind to anything older — with 159
  // celebrities driving sentiment/opinion volume, the older two-thirds
  // of the catalogue never received a single agent comment regardless
  // of quality. 200 covers the realistic active set without flooding
  // the picker (chooseParent samples uniformly within the picked surface
  // so older items now get equal odds of being chosen). The order is
  // still desc(createdAt) so that if you DO have more than 200 items in
  // a surface, the most recent are kept (oldest legacy items drop off
  // gracefully).
  const PER_SURFACE_LIMIT = 200;
  const [faceOffs, trendPolls, opinion, markets] = await Promise.all([
    db
      .select({
        parentId: matchups.id,
        title: matchups.title,
        category: matchups.category,
      })
      .from(matchups)
      .where(and(eq(matchups.isActive, true), eq(matchups.visibility, "live")))
      .orderBy(desc(matchups.createdAt))
      .limit(PER_SURFACE_LIMIT),
    db
      .select({
        parentId: trendingPolls.id,
        title: trendingPolls.headline,
        category: trendingPolls.category,
      })
      .from(trendingPolls)
      .where(eq(trendingPolls.visibility, "live"))
      .orderBy(desc(trendingPolls.createdAt))
      .limit(PER_SURFACE_LIMIT),
    db
      .select({
        parentId: opinionPolls.id,
        title: opinionPolls.title,
        category: opinionPolls.category,
      })
      .from(opinionPolls)
      .where(eq(opinionPolls.visibility, "live"))
      .orderBy(desc(opinionPolls.createdAt))
      .limit(PER_SURFACE_LIMIT),
    db
      .select({
        parentId: predictionMarkets.id,
        title: predictionMarkets.title,
        category: predictionMarkets.category,
      })
      .from(predictionMarkets)
      .where(and(
        eq(predictionMarkets.marketType, "community"),
        eq(predictionMarkets.status, "OPEN"),
        eq(predictionMarkets.visibility, "live"),
        gt(predictionMarkets.endAt, now),
      ))
      .orderBy(desc(predictionMarkets.createdAt))
      .limit(PER_SURFACE_LIMIT),
  ]);

  return [
    ...faceOffs.map((row) => ({ ...row, parentType: "matchup" as const })),
    ...trendPolls.map((row) => ({ ...row, parentType: "trending_poll" as const })),
    ...opinion.map((row) => ({ ...row, parentType: "opinion_poll" as const })),
    ...markets.map((row) => ({ ...row, parentType: "open_market" as const })),
  ];
}

/**
 * Surfaces where the agent must have already cast a vote before being
 * allowed to comment. Keeps comments tightly aligned with the agent's
 * actual position. Open markets aren't in this set — placing a bet is a
 * heavier commitment than a vote, and humans frequently comment on
 * markets they haven't bet on.
 */
const VOTE_REQUIRED_SURFACES = new Set<CommentSurface>([
  "matchup",
  "trending_poll",
  "opinion_poll",
]);

/**
 * For the given agent, return the set of `${parentType}:${parentId}`
 * keys (limited to the input parents) where the agent has already cast
 * a vote. Used to enforce the vote-first rule on matchups + polls.
 */
async function getVotedParentKeys(
  userId: string,
  parents: EligibleCommentParent[],
): Promise<Set<string>> {
  const matchupIds = parents.filter((p) => p.parentType === "matchup").map((p) => p.parentId);
  const trendingIds = parents.filter((p) => p.parentType === "trending_poll").map((p) => p.parentId);
  const opinionIds = parents.filter((p) => p.parentType === "opinion_poll").map((p) => p.parentId);

  const [matchupRows, trendingRows, opinionRows] = await Promise.all([
    matchupIds.length > 0
      ? db
          .select({ id: votes.targetId })
          .from(votes)
          .where(
            and(
              eq(votes.userId, userId),
              eq(votes.voteType, "face_off"),
              inArray(votes.targetId, matchupIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
    trendingIds.length > 0
      ? db
          .select({ id: trendingPollVotes.pollId })
          .from(trendingPollVotes)
          .where(
            and(
              eq(trendingPollVotes.userId, userId),
              inArray(trendingPollVotes.pollId, trendingIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
    opinionIds.length > 0
      ? db
          .select({ id: opinionPollVotes.pollId })
          .from(opinionPollVotes)
          .where(
            and(
              eq(opinionPollVotes.userId, userId),
              inArray(opinionPollVotes.pollId, opinionIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
  ]);

  const voted = new Set<string>();
  for (const r of matchupRows) voted.add(`matchup:${r.id}`);
  for (const r of trendingRows) voted.add(`trending_poll:${r.id}`);
  for (const r of opinionRows) voted.add(`opinion_poll:${r.id}`);
  return voted;
}

/**
 * Apply the vote-first rule: drop any parent that requires a prior vote
 * if the agent hasn't voted on it yet. Open markets always pass through.
 */
function filterByVoteRequirement(
  parents: EligibleCommentParent[],
  voted: Set<string>,
): EligibleCommentParent[] {
  return parents.filter((parent) => {
    if (!VOTE_REQUIRED_SURFACES.has(parent.parentType)) return true;
    return voted.has(`${parent.parentType}:${parent.parentId}`);
  });
}

async function getEligibleParents(userId: string, allParents?: EligibleCommentParent[]): Promise<EligibleCommentParent[]> {
  const parents = allParents ?? (await getOpenParents());
  if (!parents.length) return [];

  // We deliberately do NOT apply the vote-first filter here anymore.
  // The vote-first rule used to drop every poll/matchup the agent hadn't
  // already voted on, which combined with the daily vote sweep's "1 vote
  // per agent per day" cap meant ~80% of poll/matchup parents were
  // permanently invisible to the comment worker — pushing essentially all
  // comment volume onto open markets. We now keep all not-yet-commented
  // parents in the pool and cast a vote inline (in the main sweep loop)
  // before posting the comment whenever the parent requires one. The
  // vote-first principle is preserved (vote always lands first), but the
  // bottleneck is gone.
  const parentIds = parents.map((parent) => parent.parentId);
  const existing = await db
    .select({
      parentType: unifiedComments.parentType,
      parentId: unifiedComments.parentId,
    })
    .from(unifiedComments)
    .where(
      and(
        eq(unifiedComments.userId, userId),
        inArray(unifiedComments.parentId, parentIds),
        sql`${unifiedComments.deletedAt} IS NULL`,
      ),
    );
  const alreadyCommented = new Set(existing.map((row) => `${row.parentType}:${row.parentId}`));

  return parents.filter((parent) => !alreadyCommented.has(`${parent.parentType}:${parent.parentId}`));
}

/**
 * Per-surface target distribution. Without this, world markets dominate
 * because the pool typically has ~30 of them vs ~10-15 of each poll/matchup
 * surface — uniform random picks against count would route most comments
 * to world markets. These weights match the user's ask: roughly equal
 * representation across the four commentable surfaces with a slight tilt
 * toward polls/matchups (the more talkative surfaces on similar sites).
 */
const SURFACE_PICK_WEIGHTS: Record<CommentSurface, number> = {
  matchup: 0.30,
  trending_poll: 0.30,
  opinion_poll: 0.25,
  open_market: 0.15,
};

function chooseParent(parents: EligibleCommentParent[], profile: AgentSimulationProfile): EligibleCommentParent {
  // First pick a surface (weighted), then a parent within that surface.
  // Falls back to a uniform pick across all eligible parents only if the
  // chosen surface has nothing to offer for this agent — preserving
  // engagement when one surface temporarily has no eligible parents.
  const bySurface = new Map<CommentSurface, EligibleCommentParent[]>();
  for (const p of parents) {
    if (!bySurface.has(p.parentType)) bySurface.set(p.parentType, []);
    bySurface.get(p.parentType)!.push(p);
  }

  const availableSurfaces = (Object.keys(SURFACE_PICK_WEIGHTS) as CommentSurface[])
    .filter((s) => (bySurface.get(s)?.length ?? 0) > 0);

  if (availableSurfaces.length === 0) {
    return parents[Math.floor(Math.random() * parents.length)];
  }

  const totalWeight = availableSurfaces.reduce((sum, s) => sum + SURFACE_PICK_WEIGHTS[s], 0);
  let roll = Math.random() * totalWeight;
  let chosenSurface: CommentSurface = availableSurfaces[0];
  for (const s of availableSurfaces) {
    roll -= SURFACE_PICK_WEIGHTS[s];
    if (roll <= 0) { chosenSurface = s; break; }
  }

  const surfacePool = bySurface.get(chosenSurface)!;

  // Within the chosen surface, prefer parents in the agent's favourite
  // categories 70% of the time (when any are available). Same idea as the
  // previous chooseParent but now scoped to the picked surface so it
  // can't accidentally drag the comment back onto a world market.
  const preferred = surfacePool.filter(
    (p) => p.category && profile.favoriteCategories.includes(p.category),
  );
  const pool = preferred.length > 0 && Math.random() < 0.7 ? preferred : surfacePool;
  return pool[Math.floor(Math.random() * pool.length)];
}

/**
 * Honour the vote-first rule by casting a vote inline before commenting on
 * a poll/matchup the agent hasn't voted on yet. Returns true if the agent
 * either already had a vote on this parent or successfully cast one now.
 * Returns false when the agent is blocked (over weekly vote cap, or the
 * underlying insert no-opped due to a race) — the caller should then skip
 * this parent rather than comment without a vote.
 *
 * Open markets always pass through immediately because they don't require
 * a vote (a bet is the heavier commitment, and humans frequently comment
 * on markets they haven't bet on).
 */
async function ensureVoteBeforeComment(
  agent: { userId: string; displayName: string; contrarianism: unknown; specialties: string[] | null },
  parent: EligibleCommentParent,
  simulation: AgentSimulationProfile,
): Promise<boolean> {
  if (!VOTE_REQUIRED_SURFACES.has(parent.parentType)) return true;

  const voted = await getVotedParentKeys(agent.userId, [parent]);
  if (voted.has(`${parent.parentType}:${parent.parentId}`)) return true;

  // Respect the persona's weekly vote cap — without this an agent could
  // blow past their cap by commenting on lots of polls in one sweep.
  const weeklyVotes = await countAgentVotesThisWeek(agent.userId);
  if (weeklyVotes >= simulation.weeklyVoteCap) {
    log(`[CommentWorker] ${agent.displayName} at weekly vote cap (${weeklyVotes}/${simulation.weeklyVoteCap}), can't vote inline on ${parent.parentType}:${parent.parentId}`);
    return false;
  }

  const contrarianism = Number(agent.contrarianism ?? 0.3);
  const specialties = agent.specialties ?? [];

  let ok = false;
  switch (parent.parentType) {
    case "matchup":
      ok = await castMatchupVoteForUser(agent.userId, parent.parentId, contrarianism, specialties);
      break;
    case "trending_poll":
      ok = await castSentimentPollVoteForUser(agent.userId, parent.parentId, contrarianism);
      break;
    case "opinion_poll":
      ok = await castOpinionPollVoteForUser(agent.userId, parent.parentId, contrarianism);
      break;
  }

  if (ok) {
    log(`[CommentWorker] ${agent.displayName} voted inline on ${parent.parentType}:${parent.parentId} before commenting`);
  }
  return ok;
}

// Templates have been removed in favour of the LLM generator. The previous
// hard-coded pool produced obvious bot-flavoured comments that didn't read
// the actual prompt or vote context — we now pass full surface context to
// the model on every comment.

/** Try to find a parent + reply target for the agent. We pick a small
 *  random sample of open parents and probe each for an eligible target —
 *  no point hammering findReplyTarget on every parent in the universe.
 *  Also enforces the vote-first rule on matchups + polls. */
async function findReplyOpportunity(
  agent: { userId: string; displayName: string },
  allParents: EligibleCommentParent[],
  profile: AgentSimulationProfile,
): Promise<{ parent: EligibleCommentParent; target: ReplyTarget } | null> {
  if (!allParents.length) return null;

  // No vote-first filter here either — the main sweep loop will cast a
  // vote inline before posting the reply if the parent requires one.
  // Bias toward favoured categories first, then everything else.
  const preferred = allParents.filter(
    (p) => p.category && profile.favoriteCategories.includes(p.category),
  );
  const ordered = [...preferred.sort(() => Math.random() - 0.5), ...allParents.sort(() => Math.random() - 0.5)];
  const probed = new Set<string>();

  for (const parent of ordered) {
    const key = `${parent.parentType}:${parent.parentId}`;
    if (probed.has(key)) continue;
    probed.add(key);
    if (probed.size > 6) break;

    const target = await findReplyTarget(parent.parentType, parent.parentId, agent.userId);
    if (target) return { parent, target };
  }
  return null;
}

export async function runCommentSweep(): Promise<{
  posted: number;
  replies: number;
  /** Number of agents that tried the reply path but had no eligible
   *  target and fell back to top-level. Useful for tuning REPLY_PROBABILITY. */
  replyFallbacks: number;
  skipped: number;
  llmRejected: number;
  capReached: boolean;
}> {
  const agents = await db
    .select()
    .from(agentConfigs)
    .where(eq(agentConfigs.isActive, true));

  // Shuffle so the same agents don't always go first and dominate the
  // small daily eligibility pool.
  for (let i = agents.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [agents[i], agents[j]] = [agents[j], agents[i]];
  }

  let posted = 0;
  let replies = 0;
  let replyFallbacks = 0;
  let skipped = 0;
  let llmRejected = 0;
  let capReached = false;

  // One shared parent universe per sweep — cheaper than re-querying for
  // every agent. Each agent then derives their own eligible subset.
  const allParents = await getOpenParents();

  for (const agent of agents) {
    if (posted >= MAX_COMMENTS_PER_SWEEP) {
      capReached = true;
      skipped++;
      continue;
    }

    if (!isV2SimulationProfile(agent.simulationProfile)) {
      skipped++;
      continue;
    }

    const simulation = getSimulationProfile(agent.simulationProfile);
    if (Math.random() > simulation.dailyCommentChance) {
      skipped++;
      continue;
    }

    const weeklyCount = await countAgentCommentsThisWeek(agent.userId);
    if (weeklyCount >= simulation.weeklyCommentCap) {
      skipped++;
      continue;
    }

    let parent: EligibleCommentParent | null = null;
    let replyTarget: ReplyTarget | null = null;
    const wantedReply = Math.random() < REPLY_PROBABILITY;

    // Reply path — try first when the dice say so. If no eligible target
    // exists, fall back to top-level rather than burn the agent's slot.
    if (wantedReply) {
      const opp = await findReplyOpportunity(
        { userId: agent.userId, displayName: agent.displayName },
        allParents,
        simulation,
      );
      if (opp) {
        parent = opp.parent;
        replyTarget = opp.target;
      }
    }

    if (!parent) {
      if (wantedReply) replyFallbacks++;
      const eligible = await getEligibleParents(agent.userId, allParents);
      if (!eligible.length) {
        skipped++;
        continue;
      }
      parent = chooseParent(eligible, simulation);
    }

    // Vote-first: if this is a poll/matchup the agent hasn't voted on, cast
    // a vote inline now so the LLM can pick it up via fetchCommentContext
    // and align the comment to the chosen side. Skip the agent if the
    // inline vote can't land (over weekly cap, race-conflict, etc) rather
    // than post a comment that contradicts no stated position.
    const voteReady = await ensureVoteBeforeComment(
      { userId: agent.userId, displayName: agent.displayName, contrarianism: agent.contrarianism, specialties: agent.specialties },
      parent,
      simulation,
    );
    if (!voteReady) {
      skipped++;
      continue;
    }

    const context = await fetchCommentContext(
      parent.parentType,
      parent.parentId,
      agent.userId,
    );
    if (!context) {
      skipped++;
      log(`[CommentWorker] ${agent.displayName}: no context for ${parent.parentType}:${parent.parentId}`);
      continue;
    }

    if (replyTarget) {
      // All four CommentContext variants declare replyTarget?:, so this
      // assignment is type-safe across the union.
      context.replyTarget = replyTarget;
    }

    const agentForComment: AgentForComment = {
      displayName: agent.displayName,
      username: agent.username,
      archetype: agent.archetype,
      bio: agent.bio,
    };

    const body = await generateAgentComment(agentForComment, simulation, context);
    if (!body) {
      llmRejected++;
      skipped++;
      log(`[CommentWorker] ${agent.displayName}: LLM produced no usable comment for ${parent.parentType}${replyTarget ? " (reply)" : ""}`);
      continue;
    }

    try {
      await db.transaction(async (tx) => {
        await tx.insert(unifiedComments).values({
          parentType: parent.parentType,
          parentId: parent.parentId,
          parentCommentId: replyTarget?.commentId ?? null,
          userId: agent.userId,
          body,
        });
        await tx
          .update(profiles)
          .set({ lastActiveAt: new Date() })
          .where(eq(profiles.id, agent.userId));
      });
      posted++;
      if (replyTarget) replies++;
      log(
        `[CommentWorker] ${agent.displayName} ${replyTarget ? `replied to @${replyTarget.authorUsername ?? "user"}` : "commented"} on ${parent.parentType}:${parent.parentId} — "${body.slice(0, 80)}${body.length > 80 ? "…" : ""}"`,
      );
    } catch (err) {
      skipped++;
      log(`[CommentWorker] Failed for ${agent.displayName}: ${err instanceof Error ? err.message : err}`);
    }
  }

  return { posted, replies, replyFallbacks, skipped, llmRejected, capReached };
}

/**
 * Comment sweep cadence: every ~4 hours (with ±20 min jitter to avoid
 * predictable bursts). Previously this fired once per day at a random
 * hour, which combined with the per-agent dailyCommentChance of ~8% gave
 * the entire 56-agent cohort a 4-5 daily attempt budget — most of which
 * burned on agents already past their weekly cap. Sweeping 6x/day with
 * the new weekly cap of 3-4 produces ~10-15 visible comments/day while
 * still respecting per-persona budgets.
 *
 * dailyCommentChance is now effectively a per-sweep chance; we accept
 * that rename-by-behaviour because it gives noisy bands the volume they
 * need (0.14 × 6 = ~58% daily) without changing the field everywhere.
 */
const COMMENT_SWEEP_INTERVAL_MS = 4 * 60 * 60_000;

function msUntilNextSweep(): number {
  const jitter = Math.floor(Math.random() * 40 - 20) * 60_000;
  return Math.max(60_000, COMMENT_SWEEP_INTERVAL_MS + jitter);
}

function scheduleNextSweep(): void {
  const delay = msUntilNextSweep();
  log(`[CommentWorker] Next sweep in ${(delay / 3_600_000).toFixed(1)}h`);
  setTimeout(async () => {
    try {
      const result = await runCommentSweep();
      log(`[CommentWorker] Sweep complete: ${result.posted} posted (${result.replies} replies), ${result.skipped} skipped`);
    } catch (err) {
      console.error("[CommentWorker] Sweep failed:", err);
    }
    scheduleNextSweep();
  }, delay);
}

export function startCommentWorkerScheduler(): void {
  log(`[CommentWorker] Starting (${COMMENT_WORKER_BOOT_DELAY_MS / 1000}s boot delay, sparse daily sweep)`);
  setTimeout(async () => {
    try {
      const result = await runCommentSweep();
      log(`[CommentWorker] Initial sweep: ${result.posted} posted (${result.replies} replies), ${result.skipped} skipped`);
    } catch (err) {
      console.error("[CommentWorker] Initial sweep failed:", err);
    }
    scheduleNextSweep();
  }, COMMENT_WORKER_BOOT_DELAY_MS);
}
