/**
 * Sparse comment worker for simulated agents. It writes directly through the
 * unified comments table after resolving live parent rows, keeping volume low
 * and capped per persona.
 *
 * Comment text is generated by the LLM (server/agents/llmCommentGenerator.ts)
 * with full surface context. There is no template fallback — if generation
 * fails for an agent in a sweep, we skip them rather than post something
 * generic. Quality over quantity.
 */

import { and, count, eq, gte, inArray, sql, desc, isNull } from "drizzle-orm";
import {
  agentConfigs,
  comments as unifiedComments,
  userVotes,
  opinionPollVotes,
  profiles,
  trendingPollVotes,
  votes,
} from "@shared/schema";
import { db } from "../db";
import { log } from "../log";
import { gamificationService } from "../services/gamification";
import { awardCommentCredits, awardInsightCredits, maybeFireReferralCredit } from "../services/credits-earn";
import { checkAndAwardInsightBadges } from "../services/badges";
import {
  getSimulationProfile,
  isV2SimulationProfile,
  type AgentSimulationProfile,
} from "./simulationProfile";
import { fetchCommentContext, findReplyTarget, findInsightReplyTarget, type CommentSurface, type ReplyTarget } from "./commentContext";
import { generateAgentComment, type AgentForComment } from "./llmCommentGenerator";
import {
  castMatchupVoteForUser,
  castOpinionPollVoteForUser,
  castPersonApprovalVoteForUser,
  castSentimentPollVoteForUser,
  countAgentVotesThisWeek,
} from "./voteWorker";
import { isAgentCommentsPaused, isAgentsPaused } from "./runtime-state";
import {
  fetchMatchupParentPool,
  fetchOpenMarketParentPool,
  fetchOpinionPollParentPool,
  fetchPersonInsightParentPool,
  fetchTrendingPollParentPool,
  type CommentParentPoolStats,
} from "./commentParentPool";

/**
 * Probability that an agent's daily comment becomes a reply to someone
 * else's existing comment instead of a fresh top-level post. Replies are
 * conversational glue — too many makes the site feel like a thread farm,
 * too few looks like everyone is shouting past each other. 30% feels
 * Polymarket-natural.
 */
const REPLY_PROBABILITY = 0.30;

/**
 * Defensive cap on how many comments a single sweep can post platform-wide.
 * With 56 agents × per-sweep dailyCommentChance × weeklyCommentCap, expected
 * daily volume is ~7-8 comments. This ceiling exists so a misconfiguration
 * can't quietly generate hundreds.
 */
const MAX_COMMENTS_PER_SWEEP = 30;

const COMMENT_WORKER_BOOT_DELAY_MS = 7 * 60_000;

interface EligibleCommentParent {
  parentType: CommentSurface;
  parentId: string;
  title: string;
  category: string | null;
}

function getMondayOfWeek(): Date {
  const now = new Date();
  const day = now.getUTCDay();
  const diff = day === 0 ? 6 : day - 1;
  const monday = new Date(now);
  monday.setUTCDate(now.getUTCDate() - diff);
  monday.setUTCHours(0, 0, 0, 0);
  return monday;
}

async function countAgentCommentsThisWeek(userId: string): Promise<number> {
  const [row] = await db
    .select({ c: count() })
    .from(unifiedComments)
    .where(
      and(
        eq(unifiedComments.userId, userId),
        gte(unifiedComments.createdAt, getMondayOfWeek()),
        sql`${unifiedComments.deletedAt} IS NULL`,
      ),
    );
  return Number(row?.c ?? 0);
}

/** All currently-open parents across every commentable surface, with no
 *  per-user filtering. Reused by both the top-level path (which then
 *  excludes parents the agent has already commented on) and the reply
 *  path (which doesn't — replying to a thread you've already posted in
 *  is normal).
 *
 *  Each surface uses a hybrid pool (see commentParentPool.ts): ~70 newest
 *  plus ~130 random live rows, merged to 200. When the catalogue has ≤200
 *  live items we load all of them. chooseParent() still picks uniformly
 *  within the merged pool so explore rows get equal odds alongside recent. */
async function getOpenParents(): Promise<EligibleCommentParent[]> {
  const now = new Date();
  const [matchupPool, trendingPool, opinionPool, marketPool, personPool] = await Promise.all([
    fetchMatchupParentPool(),
    fetchTrendingPollParentPool(),
    fetchOpinionPollParentPool(),
    fetchOpenMarketParentPool(now),
    fetchPersonInsightParentPool(),
  ]);

  const poolLog = (label: string, stats: CommentParentPoolStats) =>
    `${label} recent=${stats.recent} explore=${stats.explore} merged=${stats.merged}`;

  log(
    `[CommentWorker] Parent pools: ${poolLog("matchup", matchupPool.stats)}, ` +
      `${poolLog("sentiment", trendingPool.stats)}, ` +
      `${poolLog("opinion", opinionPool.stats)}, ` +
      `${poolLog("world", marketPool.stats)}, ` +
      `${poolLog("insight", personPool.stats)}`,
  );

  return [
    ...matchupPool.rows.map((row) => ({ ...row, parentType: "matchup" as const })),
    ...trendingPool.rows.map((row) => ({ ...row, parentType: "trending_poll" as const })),
    ...opinionPool.rows.map((row) => ({ ...row, parentType: "opinion_poll" as const })),
    ...marketPool.rows.map((row) => ({ ...row, parentType: "open_market" as const })),
    ...personPool.rows.map((row) => ({ ...row, parentType: "community_insight" as const })),
  ];
}

/**
 * Surfaces where the agent must have already cast a vote before being
 * allowed to comment. Keeps comments tightly aligned with the agent's
 * actual position. Open markets aren't in this set — placing a bet is a
 * heavier commitment than a vote, and humans frequently comment on
 * markets they haven't bet on.
 */
const VOTE_REQUIRED_SURFACES = new Set<CommentSurface>([
  "matchup",
  "trending_poll",
  "opinion_poll",
]);

/**
 * For the given agent, return the set of `${parentType}:${parentId}`
 * keys (limited to the input parents) where the agent has already cast
 * a vote. Used to enforce the vote-first rule on matchups + polls.
 */
async function getVotedParentKeys(
  userId: string,
  parents: EligibleCommentParent[],
): Promise<Set<string>> {
  const matchupIds = parents.filter((p) => p.parentType === "matchup").map((p) => p.parentId);
  const trendingIds = parents.filter((p) => p.parentType === "trending_poll").map((p) => p.parentId);
  const opinionIds = parents.filter((p) => p.parentType === "opinion_poll").map((p) => p.parentId);

  const [matchupRows, trendingRows, opinionRows] = await Promise.all([
    matchupIds.length > 0
      ? db
          .select({ id: votes.targetId })
          .from(votes)
          .where(
            and(
              eq(votes.userId, userId),
              eq(votes.voteType, "face_off"),
              inArray(votes.targetId, matchupIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
    trendingIds.length > 0
      ? db
          .select({ id: trendingPollVotes.pollId })
          .from(trendingPollVotes)
          .where(
            and(
              eq(trendingPollVotes.userId, userId),
              inArray(trendingPollVotes.pollId, trendingIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
    opinionIds.length > 0
      ? db
          .select({ id: opinionPollVotes.pollId })
          .from(opinionPollVotes)
          .where(
            and(
              eq(opinionPollVotes.userId, userId),
              inArray(opinionPollVotes.pollId, opinionIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
  ]);

  const voted = new Set<string>();
  for (const r of matchupRows) voted.add(`matchup:${r.id}`);
  for (const r of trendingRows) voted.add(`trending_poll:${r.id}`);
  for (const r of opinionRows) voted.add(`opinion_poll:${r.id}`);
  return voted;
}

/**
 * Apply the vote-first rule: drop any parent that requires a prior vote
 * if the agent hasn't voted on it yet. Open markets always pass through.
 */
function filterByVoteRequirement(
  parents: EligibleCommentParent[],
  voted: Set<string>,
): EligibleCommentParent[] {
  return parents.filter((parent) => {
    if (!VOTE_REQUIRED_SURFACES.has(parent.parentType)) return true;
    return voted.has(`${parent.parentType}:${parent.parentId}`);
  });
}

async function getEligibleParents(userId: string, allParents?: EligibleCommentParent[]): Promise<EligibleCommentParent[]> {
  const parents = allParents ?? (await getOpenParents());
  if (!parents.length) return [];

  // We deliberately do NOT apply the vote-first filter here anymore.
  // The vote-first rule used to drop every poll/matchup the agent hadn't
  // already voted on, which combined with the daily vote sweep's "1 vote
  // per agent per day" cap meant ~80% of poll/matchup parents were
  // permanently invisible to the comment worker — pushing essentially all
  // comment volume onto open markets. We now keep all not-yet-commented
  // parents in the pool and cast a vote inline (in the main sweep loop)
  // before posting the comment whenever the parent requires one. The
  // vote-first principle is preserved (vote always lands first), but the
  // bottleneck is gone.

  // Split by surface: community_insight parents are PEOPLE, and the agent
  // creates top-level profile posts (comments with parentType='community_insight',
  // parentCommentId=null). The "already commented" filter for those needs to
  // query unifiedComments for top-level posts on each person. We also enforce
  // per-person caps here.
  const communityInsightParents = parents.filter((p) => p.parentType === "community_insight");
  const otherParents = parents.filter((p) => p.parentType !== "community_insight");

  const parentIds = otherParents.map((parent) => parent.parentId);
  const existing = parentIds.length > 0
    ? await db
        .select({
          parentType: unifiedComments.parentType,
          parentId: unifiedComments.parentId,
        })
        .from(unifiedComments)
        .where(
          and(
            eq(unifiedComments.userId, userId),
            inArray(unifiedComments.parentId, parentIds),
            sql`${unifiedComments.deletedAt} IS NULL`,
          ),
        )
    : [];
  const alreadyCommented = new Set(existing.map((row) => `${row.parentType}:${row.parentId}`));
  const eligibleOther = otherParents.filter(
    (parent) => !alreadyCommented.has(`${parent.parentType}:${parent.parentId}`),
  );

  const eligibleCommunityInsight = communityInsightParents.length > 0
    ? await filterEligiblePersonInsightParents(userId, communityInsightParents)
    : [];

  return [...eligibleOther, ...eligibleCommunityInsight];
}

/**
 * Per-person + per-agent caps for profile posts (community_insight surface).
 *
 * After the community_insights → comments merge, "posting an insight" =
 * writing a top-level comment with parentType='community_insight',
 * parentId=<personId>, parentCommentId=null. The caps below gate that
 * write path.
 *
 *   - Per-agent per-person: 1 insight / 14 days. Prevents the same agent
 *     camping one celebrity. Longer than the 7-day default for cards because
 *     profiles are stickier — re-commenting on the same person every week
 *     reads as bot-like.
 *   - Platform-wide per-person: 2 agent insights / 7 days. Prevents the
 *     profile feeling astroturfed when multiple agents land on the same
 *     celebrity in the same week.
 *
 * Reply targets are handled separately by findInsightReplyTarget (no caps —
 * replies are conversational, not new posts).
 */
async function filterEligiblePersonInsightParents(
  userId: string,
  parents: EligibleCommentParent[],
): Promise<EligibleCommentParent[]> {
  const personIds = parents.map((p) => p.parentId);
  const fourteenDaysAgo = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);

  // Per-agent per-person cap: skip persons this agent has already posted a
  // top-level profile post on in the last 14 days. After the merge, top-level
  // posts are comments with parentType='community_insight', parentCommentId=null.
  const agentPosts = await db
    .select({ personId: unifiedComments.parentId })
    .from(unifiedComments)
    .where(
      and(
        eq(unifiedComments.userId, userId),
        eq(unifiedComments.parentType, "community_insight"),
        isNull(unifiedComments.parentCommentId),
        inArray(unifiedComments.parentId, personIds),
        isNull(unifiedComments.deletedAt),
        sql`${unifiedComments.createdAt} >= ${fourteenDaysAgo}`,
      ),
    );
  const agentPersonSet = new Set(agentPosts.map((r) => r.personId));

  // Platform cap: count agent-authored top-level profile posts per person in
  // the last 7 days, skip persons already at 2+. Join with profiles to filter isAgent.
  const platformPosts = await db
    .select({ personId: unifiedComments.parentId, n: count() })
    .from(unifiedComments)
    .leftJoin(profiles, eq(unifiedComments.userId, profiles.id))
    .where(
      and(
        eq(unifiedComments.parentType, "community_insight"),
        isNull(unifiedComments.parentCommentId),
        inArray(unifiedComments.parentId, personIds),
        isNull(unifiedComments.deletedAt),
        sql`${unifiedComments.createdAt} >= ${sevenDaysAgo}`,
        eq(profiles.isAgent, true),
      ),
    )
    .groupBy(unifiedComments.parentId);
  const platformCappedSet = new Set(
    platformPosts.filter((r) => Number(r.n) >= 2).map((r) => r.personId),
  );

  return parents.filter(
    (p) => !agentPersonSet.has(p.parentId) && !platformCappedSet.has(p.parentId),
  );
}

/**
 * Pile-on safeguard for profile posts. Before an agent posts, look at the
 * last 10 top-level profile posts on this person. If 8+ lean the same
 * direction (by the author's approval rating: positive = 4-5, negative =
 * 1-2, neutral = 3) AND the agent was about to lean the same way, roll a
 * 50% skip chance. Prevents the "everyone loves Ronaldo" effect that would
 * otherwise make agent commenting read as coordinated.
 *
 * After the community_insights → comments merge, top-level posts are
 * comments with parentType='community_insight', parentCommentId=null.
 *
 * Returns true when the agent should skip this person this sweep.
 */
async function shouldSkipForPileOn(
  personId: string,
  intendedLean: "positive" | "negative" | "neutral" | "none",
): Promise<boolean> {
  if (intendedLean === "none") return false;

  const recentPosts = await db
    .select({ userId: unifiedComments.userId })
    .from(unifiedComments)
    .where(
      and(
        eq(unifiedComments.parentType, "community_insight"),
        eq(unifiedComments.parentId, personId),
        isNull(unifiedComments.parentCommentId),
        isNull(unifiedComments.deletedAt),
      ),
    )
    .orderBy(desc(unifiedComments.createdAt))
    .limit(10);

  // Need at least 10 posts to meaningfully detect a pile-on.
  if (recentPosts.length < 8) return false;

  const userIds = recentPosts.map((i) => i.userId);
  const ratings = await db
    .select({ userId: userVotes.userId, rating: userVotes.rating })
    .from(userVotes)
    .where(
      and(
        eq(userVotes.personId, personId),
        inArray(userVotes.userId, userIds),
      ),
    );
  const ratingByUser = new Map(ratings.map((r) => [r.userId, Number(r.rating)]));

  let positive = 0;
  let negative = 0;
  let neutral = 0;
  for (const post of recentPosts) {
    const rating = ratingByUser.get(post.userId);
    if (rating == null) continue;
    if (rating >= 4) positive++;
    else if (rating <= 2) negative++;
    else neutral++;
  }

  const sameDirection =
    intendedLean === "positive" ? positive : intendedLean === "negative" ? negative : neutral;
  if (sameDirection >= 8) {
    // 50% skip chance to break the pile-on.
    return Math.random() < 0.5;
  }
  return false;
}

/**
 * Per-surface target distribution. Without this, world markets dominate
 * because the pool typically has ~30 of them vs ~10-15 of each poll/matchup
 * surface — uniform random picks against count would route most comments
 * to world markets. These weights match the user's ask: roughly equal
 * representation across the four commentable surfaces with a slight tilt
 * toward polls/matchups (the more talkative surfaces on similar sites).
 */
const SURFACE_PICK_WEIGHTS: Record<CommentSurface, number> = {
  matchup: 0.25,
  trending_poll: 0.25,
  opinion_poll: 0.20,
  open_market: 0.10,
  // Profile insights debut at 20% (moderate cadence per the user's decision)
  // so agents post a meaningful number of celebrity opinions without
  // flooding profiles. Per-person + per-agent caps in filterEligiblePersonInsightParents
  // keep volume bounded even if this weight is later raised.
  community_insight: 0.20,
};

function chooseParent(parents: EligibleCommentParent[], profile: AgentSimulationProfile): EligibleCommentParent {
  // First pick a surface (weighted), then a parent within that surface.
  // Falls back to a uniform pick across all eligible parents only if the
  // chosen surface has nothing to offer for this agent — preserving
  // engagement when one surface temporarily has no eligible parents.
  const bySurface = new Map<CommentSurface, EligibleCommentParent[]>();
  for (const p of parents) {
    if (!bySurface.has(p.parentType)) bySurface.set(p.parentType, []);
    bySurface.get(p.parentType)!.push(p);
  }

  const availableSurfaces = (Object.keys(SURFACE_PICK_WEIGHTS) as CommentSurface[])
    .filter((s) => (bySurface.get(s)?.length ?? 0) > 0);

  if (availableSurfaces.length === 0) {
    return parents[Math.floor(Math.random() * parents.length)];
  }

  const totalWeight = availableSurfaces.reduce((sum, s) => sum + SURFACE_PICK_WEIGHTS[s], 0);
  let roll = Math.random() * totalWeight;
  let chosenSurface: CommentSurface = availableSurfaces[0];
  for (const s of availableSurfaces) {
    roll -= SURFACE_PICK_WEIGHTS[s];
    if (roll <= 0) { chosenSurface = s; break; }
  }

  const surfacePool = bySurface.get(chosenSurface)!;

  // Within the chosen surface, prefer parents in the agent's favourite
  // categories 70% of the time (when any are available). Same idea as the
  // previous chooseParent but now scoped to the picked surface so it
  // can't accidentally drag the comment back onto a world market.
  const preferred = surfacePool.filter(
    (p) => p.category && profile.favoriteCategories.includes(p.category),
  );
  const pool = preferred.length > 0 && Math.random() < 0.7 ? preferred : surfacePool;
  return pool[Math.floor(Math.random() * pool.length)];
}

/**
 * Honour the vote-first rule by casting a vote inline before commenting on
 * a poll/matchup the agent hasn't voted on yet. Returns true if the agent
 * either already had a vote on this parent or successfully cast one now.
 * Returns false when the agent is blocked (over weekly vote cap, or the
 * underlying insert no-opped due to a race) — the caller should then skip
 * this parent rather than comment without a vote.
 *
 * Open markets always pass through immediately because they don't require
 * a vote (a bet is the heavier commitment, and humans frequently comment
 * on markets they haven't bet on).
 */
async function ensureVoteBeforeComment(
  agent: { userId: string; displayName: string; contrarianism: unknown; prestigeBias: unknown; specialties: string[] | null },
  parent: EligibleCommentParent,
  simulation: AgentSimulationProfile,
): Promise<boolean> {
  // Community_insight: cast a person approval vote (or noisy-skip per the
  // hybrid sentiment model). The agent always proceeds to comment — the
  // vote is a stance marker that the LLM aligns with, not a gate that
  // blocks commenting. Returns true regardless of vote outcome.
  if (parent.parentType === "community_insight") {
    const contrarianism = Number(agent.contrarianism ?? 0.3);
    const prestigeBias = Number(agent.prestigeBias ?? 0.5);
    const rating = await castPersonApprovalVoteForUser(
      agent.userId,
      parent.parentId,
      parent.title, // person name from the parent pool
      contrarianism,
      prestigeBias,
      simulation,
      null, // currentAvg — null for now; decideApprovalRating defaults to 3
    );
    if (rating != null) {
      log(`[CommentWorker] ${agent.displayName} rated ${parent.title} ${rating}/5 before commenting`);
    } else {
      log(`[CommentWorker] ${agent.displayName} posting on ${parent.title} without a rating (noisy-skip or vote cap)`);
    }
    return true;
  }

  if (!VOTE_REQUIRED_SURFACES.has(parent.parentType)) return true;

  const voted = await getVotedParentKeys(agent.userId, [parent]);
  if (voted.has(`${parent.parentType}:${parent.parentId}`)) return true;

  // Respect the persona's weekly vote cap — without this an agent could
  // blow past their cap by commenting on lots of polls in one sweep.
  const weeklyVotes = await countAgentVotesThisWeek(agent.userId);
  if (weeklyVotes >= simulation.weeklyVoteCap) {
    log(`[CommentWorker] ${agent.displayName} at weekly vote cap (${weeklyVotes}/${simulation.weeklyVoteCap}), can't vote inline on ${parent.parentType}:${parent.parentId}`);
    return false;
  }

  const contrarianism = Number(agent.contrarianism ?? 0.3);
  const specialties = agent.specialties ?? [];

  let ok = false;
  switch (parent.parentType) {
    case "matchup":
      ok = await castMatchupVoteForUser(agent.userId, parent.parentId, contrarianism, specialties);
      break;
    case "trending_poll":
      ok = await castSentimentPollVoteForUser(agent.userId, parent.parentId, contrarianism);
      break;
    case "opinion_poll":
      ok = await castOpinionPollVoteForUser(agent.userId, parent.parentId, contrarianism);
      break;
  }

  if (ok) {
    log(`[CommentWorker] ${agent.displayName} voted inline on ${parent.parentType}:${parent.parentId} before commenting`);
  }
  return ok;
}

// Templates have been removed in favour of the LLM generator. The previous
// hard-coded pool produced obvious bot-flavoured comments that didn't read
// the actual prompt or vote context — we now pass full surface context to
// the model on every comment.

/** Try to find a parent + reply target for the agent. We probe a small
 *  random sample of open parents (≤6) for an eligible target — no point
 *  hammering findReplyTarget on every parent in the universe. The probe
 *  order is weighted by SURFACE_PICK_WEIGHTS (same distribution as the
 *  top-level picker) so replies don't accidentally drift onto whichever
 *  surface happens to have the most parents — without this the world-
 *  market surface (typically the largest) would dominate replies even
 *  when polls/matchups have rich active threads. */
async function findReplyOpportunity(
  agent: { userId: string; displayName: string },
  allParents: EligibleCommentParent[],
  profile: AgentSimulationProfile,
): Promise<{ parent: EligibleCommentParent; target: ReplyTarget } | null> {
  if (!allParents.length) return null;

  // Build per-surface buckets so we can weight the probe order.
  const bySurface = new Map<CommentSurface, EligibleCommentParent[]>();
  for (const p of allParents) {
    if (!bySurface.has(p.parentType)) bySurface.set(p.parentType, []);
    bySurface.get(p.parentType)!.push(p);
  }

  // Within each bucket, prefer the agent's favourite categories first
  // (same bias the top-level path applies), then shuffle the rest.
  const preparedBuckets = new Map<CommentSurface, EligibleCommentParent[]>();
  for (const [surface, parents] of bySurface.entries()) {
    const preferred = parents.filter(
      (p) => p.category && profile.favoriteCategories.includes(p.category),
    );
    const others = parents.filter((p) => !preferred.includes(p));
    preparedBuckets.set(surface, [
      ...preferred.sort(() => Math.random() - 0.5),
      ...others.sort(() => Math.random() - 0.5),
    ]);
  }

  // Generate a weighted probe order: pick up to 6 parents by sampling
  // surface-by-weight, then taking the next unconsumed parent from that
  // surface's prepared queue. This mirrors chooseParent's distribution
  // while staying probe-cheap.
  const probed = new Set<string>();
  const cursors = new Map<CommentSurface, number>();
  const surfaces = Array.from(preparedBuckets.keys());

  while (probed.size < 6) {
    const availableSurfaces = surfaces.filter(
      (s) => (cursors.get(s) ?? 0) < (preparedBuckets.get(s)?.length ?? 0),
    );
    if (availableSurfaces.length === 0) break;

    const totalWeight = availableSurfaces.reduce(
      (sum, s) => sum + SURFACE_PICK_WEIGHTS[s],
      0,
    );
    let roll = Math.random() * totalWeight;
    let chosen: CommentSurface = availableSurfaces[0];
    for (const s of availableSurfaces) {
      roll -= SURFACE_PICK_WEIGHTS[s];
      if (roll <= 0) {
        chosen = s;
        break;
      }
    }

    const cursor = cursors.get(chosen) ?? 0;
    const parent = preparedBuckets.get(chosen)![cursor];
    cursors.set(chosen, cursor + 1);

    const key = `${parent.parentType}:${parent.parentId}`;
    if (probed.has(key)) continue;
    probed.add(key);

    // For community_insight, the parent is a PERSON — findReplyTarget
    // (which queries unifiedComments for a specific parentId) doesn't
    // apply. Instead, find a human-authored top-level insight on this
    // person that the agent can reply to.
    const target = parent.parentType === "community_insight"
      ? await findInsightReplyTarget(parent.parentId, agent.userId)
      : await findReplyTarget(parent.parentType, parent.parentId, agent.userId);
    if (target) return { parent, target };
  }
  return null;
}

export async function runCommentSweep(): Promise<{
  posted: number;
  replies: number;
  /** Number of agents that tried the reply path but had no eligible
   *  target and fell back to top-level. Useful for tuning REPLY_PROBABILITY. */
  replyFallbacks: number;
  skipped: number;
  llmRejected: number;
  capReached: boolean;
  /** Number of agents whose first-pick parent failed the vote-first rule
   *  (vote cap reached or inline vote couldn't land), but who recovered by
   *  re-rolling onto a vote-friendly parent. Surfaces tuning signal for
   *  weekly vote cap headroom. */
  voteCapDeflections: number;
  /** Number of agents whose entire eligible pool was vote-blocked
   *  (no open markets and no already-voted polls/matchups left to comment
   *  on). When this stays high, the cap needs to go up. */
  voteCapBlocked: number;
  /** Per-surface count of comments actually posted in this sweep.
   *  Single most useful signal for confirming the surface distribution
   *  matches SURFACE_PICK_WEIGHTS — if this is 100% open_market the
   *  picker filter is broken regardless of what other counters say. */
  bySurface: Record<CommentSurface, number>;
  /** Of the replies posted this sweep, how many landed at thread depth 2
   *  (reply-to-a-reply). Counter for the nested-reply experiment — if it
   *  trends high we may want to dial AGENT_MAX_REPLY_DEPTH back to 0. */
  nestedReplies: number;
}> {
  // Global "pause all agents" kill switch (admin Agents tab toggle).
  if (await isAgentsPaused()) {
    log("[CommentWorker] Skipping sweep; agents are globally paused");
    return {
      posted: 0,
      replies: 0,
      replyFallbacks: 0,
      skipped: 0,
      llmRejected: 0,
      capReached: false,
      voteCapDeflections: 0,
      voteCapBlocked: 0,
      bySurface: {} as Record<CommentSurface, number>,
      nestedReplies: 0,
    };
  }

  if (await isAgentCommentsPaused()) {
    log("[CommentWorker] Skipping sweep; agent commenting is paused");
    return {
      posted: 0,
      replies: 0,
      replyFallbacks: 0,
      skipped: 0,
      llmRejected: 0,
      capReached: false,
      voteCapDeflections: 0,
      voteCapBlocked: 0,
      bySurface: {} as Record<CommentSurface, number>,
      nestedReplies: 0,
    };
  }

  const agents = await db
    .select()
    .from(agentConfigs)
    .where(eq(agentConfigs.isActive, true));

  for (let i = agents.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [agents[i], agents[j]] = [agents[j], agents[i]];
  }

  let posted = 0;
  let replies = 0;
  let nestedReplies = 0;
  let replyFallbacks = 0;
  let skipped = 0;
  let llmRejected = 0;
  let capReached = false;
  let voteCapDeflections = 0;
  let voteCapBlocked = 0;
  const bySurface: Record<CommentSurface, number> = {
    matchup: 0,
    trending_poll: 0,
    opinion_poll: 0,
    open_market: 0,
    community_insight: 0,
  };

  const allParents = await getOpenParents();

  for (const agent of agents) {
    if (posted >= MAX_COMMENTS_PER_SWEEP) {
      capReached = true;
      skipped++;
      continue;
    }

    if (!isV2SimulationProfile(agent.simulationProfile)) {
      skipped++;
      continue;
    }

    const simulation = getSimulationProfile(agent.simulationProfile);
    if (Math.random() > simulation.dailyCommentChance) {
      skipped++;
      continue;
    }

    const weeklyCount = await countAgentCommentsThisWeek(agent.userId);
    if (weeklyCount >= simulation.weeklyCommentCap) {
      skipped++;
      continue;
    }

    // ── Vote-cap-aware parent filtering ────────────────────────────────
    // Previously: when the surface picker landed on a poll/matchup the
    // agent hadn't voted on AND the agent was at their weekly vote cap,
    // ensureVoteBeforeComment returned false and the agent was silently
    // skipped for the entire sweep. With ~75% of pick weight on vote-
    // required surfaces and uniform random within each surface, this
    // funnelled almost all comment volume onto open markets once agents
    // hit their vote cap mid-week (which happens by Wed-Thu).
    //
    // Fix: pre-compute voted parents and weekly vote count, then if the
    // agent is at vote cap restrict the candidate pool to "vote-cap
    // friendly" parents only — open markets (no vote needed) plus polls/
    // matchups they've already voted on. The picker then always lands on
    // something that will pass ensureVoteBeforeComment, preserving
    // surface distribution even under cap pressure.
    const votedSet = await getVotedParentKeys(agent.userId, allParents);
    const weeklyVotes = await countAgentVotesThisWeek(agent.userId);
    const atVoteCap = weeklyVotes >= simulation.weeklyVoteCap;

    const candidatePool = atVoteCap
      ? allParents.filter(
          (p) =>
            !VOTE_REQUIRED_SURFACES.has(p.parentType) ||
            votedSet.has(`${p.parentType}:${p.parentId}`),
        )
      : allParents;

    if (atVoteCap && candidatePool.length === 0) {
      voteCapBlocked++;
      skipped++;
      continue;
    }

    let parent: EligibleCommentParent | null = null;
    let replyTarget: ReplyTarget | null = null;
    const wantedReply = Math.random() < REPLY_PROBABILITY;

    if (wantedReply) {
      const opp = await findReplyOpportunity(
        { userId: agent.userId, displayName: agent.displayName },
        candidatePool,
        simulation,
      );
      if (opp) {
        parent = opp.parent;
        replyTarget = opp.target;
      }
    }

    if (!parent) {
      if (wantedReply) replyFallbacks++;
      const eligible = await getEligibleParents(agent.userId, candidatePool);
      if (!eligible.length) {
        skipped++;
        continue;
      }
      parent = chooseParent(eligible, simulation);
    }

    // Vote-first: cast inline vote on poll/matchup parents the agent
    // hasn't voted on yet. With the candidatePool filter above, this
    // should now only fire when the agent has vote budget — but we
    // still re-roll once on race-condition failure (e.g. someone else
    // bumped their vote count between the cap check and the cast)
    // before giving up on the agent.
    let voteReady = await ensureVoteBeforeComment(
      { userId: agent.userId, displayName: agent.displayName, contrarianism: agent.contrarianism, prestigeBias: agent.prestigeBias, specialties: agent.specialties },
      parent,
      simulation,
    );
    if (!voteReady) {
      // Parent's vote couldn't land (cap reached mid-sweep or DB race).
      // Try once more from the vote-cap-friendly pool — open markets and
      // already-voted polls — rather than silently dropping the agent.
      const safePool = allParents.filter(
        (p) =>
          !VOTE_REQUIRED_SURFACES.has(p.parentType) ||
          votedSet.has(`${p.parentType}:${p.parentId}`),
      );
      const safeEligible = await getEligibleParents(agent.userId, safePool);
      if (safeEligible.length === 0) {
        voteCapBlocked++;
        skipped++;
        continue;
      }
      parent = chooseParent(safeEligible, simulation);
      replyTarget = null; // reply target was tied to original parent
      voteReady = await ensureVoteBeforeComment(
        { userId: agent.userId, displayName: agent.displayName, contrarianism: agent.contrarianism, prestigeBias: agent.prestigeBias, specialties: agent.specialties },
        parent,
        simulation,
      );
      if (!voteReady) {
        // Should be unreachable — safePool only contains parents that
        // either don't need a vote or already have one. If we land here
        // it's a real bug worth surfacing.
        log(`[CommentWorker] ${agent.displayName}: vote-safe re-roll still failed on ${parent.parentType}:${parent.parentId}`);
        skipped++;
        continue;
      }
      voteCapDeflections++;
    }

    const context = await fetchCommentContext(
      parent.parentType,
      parent.parentId,
      agent.userId,
    );
    if (!context) {
      skipped++;
      log(`[CommentWorker] ${agent.displayName}: no context for ${parent.parentType}:${parent.parentId}`);
      continue;
    }

    if (replyTarget) {
      // All four CommentContext variants declare replyTarget?:, so this
      // assignment is type-safe across the union.
      context.replyTarget = replyTarget;
    }

    // Pile-on safeguard for profile insights: if the last 10 insights on
    // this person skew 8+ in the same direction as the agent's intended
    // lean, 50% chance to skip. Prevents "everyone loves Ronaldo" effects.
    // Only applies to top-level insight creation (not replies — replies
    // are conversational and the parent insight already breaks any pile-on).
    if (parent.parentType === "community_insight" && !replyTarget) {
      const ratingStr = (context as { agentChoice?: string | null }).agentChoice;
      const rating = ratingStr ? Number(ratingStr) : NaN;
      const intendedLean: "positive" | "negative" | "neutral" | "none" =
        Number.isFinite(rating) && rating >= 4 ? "positive"
        : Number.isFinite(rating) && rating <= 2 ? "negative"
        : Number.isFinite(rating) && rating === 3 ? "neutral"
        : "none";
      if (await shouldSkipForPileOn(parent.parentId, intendedLean)) {
        skipped++;
        log(`[CommentWorker] ${agent.displayName} skipped ${parent.title} to break pile-on (lean=${intendedLean})`);
        continue;
      }
    }

    const agentForComment: AgentForComment = {
      displayName: agent.displayName,
      username: agent.username,
      archetype: agent.archetype,
      bio: agent.bio,
    };

    const body = await generateAgentComment(agentForComment, simulation, context);
    if (!body) {
      llmRejected++;
      skipped++;
      log(`[CommentWorker] ${agent.displayName}: LLM produced no usable comment for ${parent.parentType}${replyTarget ? " (reply)" : ""}`);
      continue;
    }

    try {
      const trimmedContent = body.trim();
      const isCommunityInsight = parent.parentType === "community_insight";
      const isTopLevelProfilePost = isCommunityInsight && !replyTarget;
      const shouldAwardXp = isCommunityInsight && trimmedContent.length >= 20;

      const newCommentId = await db.transaction(async (tx) => {
        // After the community_insights → comments merge, every surface writes
        // to unified comments. Top-level profile posts use parentType=
        // 'community_insight', parentId=<personId>, parentCommentId=null;
        // replies to them use parentCommentId=<topLevelCommentId>. Other
        // surfaces unchanged.
        const [newComment] = await tx
          .insert(unifiedComments)
          .values({
            parentType: parent.parentType,
            parentId: parent.parentId,
            parentCommentId: replyTarget?.commentId ?? null,
            userId: agent.userId,
            body,
          })
          .returning({ id: unifiedComments.id });
        await tx
          .update(profiles)
          .set({ lastActiveAt: new Date() })
          .where(eq(profiles.id, agent.userId));
        return newComment.id;
      });

      if (shouldAwardXp) {
        if (isTopLevelProfilePost) {
          // Top-level profile post: mirror the human insight creation path —
          // post_insight XP + insight credits + insight badges + referral.
          // Makes agent accounts accrue the same rewards humans do. The
          // newCommentId is the top-level comment's id (preserved as the
          // insight id for credit/XP idempotency keys).
          try {
            await gamificationService.awardXp(
              agent.userId,
              "post_insight",
              `insight_${newCommentId}_${agent.userId}`,
              { insightId: newCommentId, personId: parent.parentId },
            );
          } catch (e) {
            log(`[CommentWorker] XP award failed for ${agent.displayName}: ${e}`);
          }
          try {
            await awardInsightCredits(agent.userId, newCommentId, { personId: parent.parentId });
          } catch (e) {
            log(`[CommentWorker] insight credits failed for ${agent.displayName}: ${e}`);
          }
          try {
            await checkAndAwardInsightBadges(agent.userId);
          } catch (e) {
            log(`[CommentWorker] insight badges failed for ${agent.displayName}: ${e}`);
          }
          await maybeFireReferralCredit(agent.userId);
        } else {
          // Reply to a profile post: post_comment XP + comment credits + referral.
          // The insightId in metadata is the top-level comment being replied to
          // (for audit trail), not the new comment id.
          const insightIdForMetadata = replyTarget?.commentId ?? parent.parentId;
          try {
            await gamificationService.awardXp(
              agent.userId,
              "post_comment",
              `comment_${newCommentId}_${agent.userId}`,
              { commentId: newCommentId, insightId: insightIdForMetadata },
            );
          } catch (e) {
            log(`[CommentWorker] XP award failed for ${agent.displayName}: ${e}`);
          }
          await awardCommentCredits(agent.userId, newCommentId, {
            insightId: insightIdForMetadata,
          });
          await maybeFireReferralCredit(agent.userId);
        }
      }

      posted++;
      if (replyTarget) {
        replies++;
        // threadRoot is populated only when the target was itself a reply
        // (depth 1) — so this reply lands at depth 2.
        if (replyTarget.threadRoot) nestedReplies++;
      }
      bySurface[parent.parentType]++;
      const replyTag = replyTarget
        ? replyTarget.threadRoot
          ? `nested-replied to @${replyTarget.authorUsername ?? "user"}`
          : `replied to @${replyTarget.authorUsername ?? "user"}`
        : "commented";
      log(
        `[CommentWorker] ${agent.displayName} ${replyTag} on ${parent.parentType}:${parent.parentId} — "${body.slice(0, 80)}${body.length > 80 ? "…" : ""}"`,
      );
    } catch (err) {
      skipped++;
      log(`[CommentWorker] Failed for ${agent.displayName}: ${err instanceof Error ? err.message : err}`);
    }
  }

  return {
    posted,
    replies,
    replyFallbacks,
    skipped,
    llmRejected,
    capReached,
    voteCapDeflections,
    voteCapBlocked,
    bySurface,
    nestedReplies,
  };
}

/**
 * Comment sweep cadence: every ~4 hours (with ±20 min jitter to avoid
 * predictable bursts). Sweeping ~6x/day with per-sweep dailyCommentChance
 * (noisy 0.034, casual 0.020, others 0.013) yields ~7-8 visible comments/day
 * while respecting weeklyCommentCap per persona.
 *
 * dailyCommentChance is effectively a per-sweep probability, not once daily.
 */
const COMMENT_SWEEP_INTERVAL_MS = 4 * 60 * 60_000;

function msUntilNextSweep(): number {
  const jitter = Math.floor(Math.random() * 40 - 20) * 60_000;
  return Math.max(60_000, COMMENT_SWEEP_INTERVAL_MS + jitter);
}

function scheduleNextSweep(): void {
  const delay = msUntilNextSweep();
  log(`[CommentWorker] Next sweep in ${(delay / 3_600_000).toFixed(1)}h`);
  setTimeout(async () => {
    try {
      const result = await runCommentSweep();
      log(
        `[CommentWorker] Sweep complete: ${result.posted} posted ` +
          `[matchup:${result.bySurface.matchup}, sentiment:${result.bySurface.trending_poll}, opinion:${result.bySurface.opinion_poll}, world:${result.bySurface.open_market}, insight:${result.bySurface.community_insight}] ` +
          `(${result.replies} replies, ${result.nestedReplies} nested, ${result.voteCapDeflections} vote-cap deflections, ${result.voteCapBlocked} vote-cap blocked), ${result.skipped} skipped`,
      );
    } catch (err) {
      console.error("[CommentWorker] Sweep failed:", err);
    }
    scheduleNextSweep();
  }, delay);
}

export function startCommentWorkerScheduler(): void {
  log(`[CommentWorker] Starting (${COMMENT_WORKER_BOOT_DELAY_MS / 1000}s boot delay, sparse daily sweep)`);
  setTimeout(async () => {
    try {
      const result = await runCommentSweep();
      log(
        `[CommentWorker] Initial sweep: ${result.posted} posted ` +
          `[matchup:${result.bySurface.matchup}, sentiment:${result.bySurface.trending_poll}, opinion:${result.bySurface.opinion_poll}, world:${result.bySurface.open_market}, insight:${result.bySurface.community_insight}] ` +
          `(${result.replies} replies, ${result.nestedReplies} nested, ${result.voteCapDeflections} vote-cap deflections, ${result.voteCapBlocked} vote-cap blocked), ${result.skipped} skipped`,
      );
    } catch (err) {
      console.error("[CommentWorker] Initial sweep failed:", err);
    }
    scheduleNextSweep();
  }, COMMENT_WORKER_BOOT_DELAY_MS);
}
