/**
 * Sparse comment worker for simulated agents. It writes directly through the
 * unified comments table after resolving live parent rows, keeping volume low
 * and capped per persona.
 *
 * Comment text is generated by the LLM (server/agents/llmCommentGenerator.ts)
 * with full surface context. There is no template fallback — if generation
 * fails for an agent in a sweep, we skip them rather than post something
 * generic. Quality over quantity.
 */

import { and, count, desc, eq, gt, gte, inArray, sql } from "drizzle-orm";
import {
  agentConfigs,
  comments as unifiedComments,
  matchups,
  opinionPolls,
  opinionPollVotes,
  predictionMarkets,
  profiles,
  trendingPolls,
  trendingPollVotes,
  votes,
} from "@shared/schema";
import { db } from "../db";
import { log } from "../log";
import {
  getSimulationProfile,
  isV2SimulationProfile,
  type AgentSimulationProfile,
} from "./simulationProfile";
import { fetchCommentContext, findReplyTarget, type CommentSurface, type ReplyTarget } from "./commentContext";
import { generateAgentComment, type AgentForComment } from "./llmCommentGenerator";

/**
 * Probability that an agent's daily comment becomes a reply to someone
 * else's existing comment instead of a fresh top-level post. Replies are
 * conversational glue — too many makes the site feel like a thread farm,
 * too few looks like everyone is shouting past each other. 30% feels
 * Polymarket-natural.
 */
const REPLY_PROBABILITY = 0.30;

/**
 * Defensive cap on how many comments a single sweep can post platform-wide.
 * With 56 agents × ~10% daily chance × weeklyCap=1, expected daily volume is
 * 3-6 comments. This ceiling exists so a misconfiguration can't quietly
 * generate hundreds.
 */
const MAX_COMMENTS_PER_SWEEP = 30;

const COMMENT_WORKER_BOOT_DELAY_MS = 7 * 60_000;

interface EligibleCommentParent {
  parentType: CommentSurface;
  parentId: string;
  title: string;
  category: string | null;
}

function getMondayOfWeek(): Date {
  const now = new Date();
  const day = now.getUTCDay();
  const diff = day === 0 ? 6 : day - 1;
  const monday = new Date(now);
  monday.setUTCDate(now.getUTCDate() - diff);
  monday.setUTCHours(0, 0, 0, 0);
  return monday;
}

async function countAgentCommentsThisWeek(userId: string): Promise<number> {
  const [row] = await db
    .select({ c: count() })
    .from(unifiedComments)
    .where(
      and(
        eq(unifiedComments.userId, userId),
        gte(unifiedComments.createdAt, getMondayOfWeek()),
        sql`${unifiedComments.deletedAt} IS NULL`,
      ),
    );
  return Number(row?.c ?? 0);
}

/** All currently-open parents across every commentable surface, with no
 *  per-user filtering. Reused by both the top-level path (which then
 *  excludes parents the agent has already commented on) and the reply
 *  path (which doesn't — replying to a thread you've already posted in
 *  is normal). */
async function getOpenParents(): Promise<EligibleCommentParent[]> {
  const now = new Date();
  const [faceOffs, trendPolls, opinion, markets] = await Promise.all([
    db
      .select({
        parentId: matchups.id,
        title: matchups.title,
        category: matchups.category,
      })
      .from(matchups)
      .where(and(eq(matchups.isActive, true), eq(matchups.visibility, "live")))
      .orderBy(desc(matchups.createdAt))
      .limit(30),
    db
      .select({
        parentId: trendingPolls.id,
        title: trendingPolls.headline,
        category: trendingPolls.category,
      })
      .from(trendingPolls)
      .where(eq(trendingPolls.visibility, "live"))
      .orderBy(desc(trendingPolls.createdAt))
      .limit(30),
    db
      .select({
        parentId: opinionPolls.id,
        title: opinionPolls.title,
        category: opinionPolls.category,
      })
      .from(opinionPolls)
      .where(eq(opinionPolls.visibility, "live"))
      .orderBy(desc(opinionPolls.createdAt))
      .limit(30),
    db
      .select({
        parentId: predictionMarkets.id,
        title: predictionMarkets.title,
        category: predictionMarkets.category,
      })
      .from(predictionMarkets)
      .where(and(
        eq(predictionMarkets.marketType, "community"),
        eq(predictionMarkets.status, "OPEN"),
        eq(predictionMarkets.visibility, "live"),
        gt(predictionMarkets.endAt, now),
      ))
      .orderBy(desc(predictionMarkets.createdAt))
      .limit(30),
  ]);

  return [
    ...faceOffs.map((row) => ({ ...row, parentType: "matchup" as const })),
    ...trendPolls.map((row) => ({ ...row, parentType: "trending_poll" as const })),
    ...opinion.map((row) => ({ ...row, parentType: "opinion_poll" as const })),
    ...markets.map((row) => ({ ...row, parentType: "open_market" as const })),
  ];
}

/**
 * Surfaces where the agent must have already cast a vote before being
 * allowed to comment. Keeps comments tightly aligned with the agent's
 * actual position. Open markets aren't in this set — placing a bet is a
 * heavier commitment than a vote, and humans frequently comment on
 * markets they haven't bet on.
 */
const VOTE_REQUIRED_SURFACES = new Set<CommentSurface>([
  "matchup",
  "trending_poll",
  "opinion_poll",
]);

/**
 * For the given agent, return the set of `${parentType}:${parentId}`
 * keys (limited to the input parents) where the agent has already cast
 * a vote. Used to enforce the vote-first rule on matchups + polls.
 */
async function getVotedParentKeys(
  userId: string,
  parents: EligibleCommentParent[],
): Promise<Set<string>> {
  const matchupIds = parents.filter((p) => p.parentType === "matchup").map((p) => p.parentId);
  const trendingIds = parents.filter((p) => p.parentType === "trending_poll").map((p) => p.parentId);
  const opinionIds = parents.filter((p) => p.parentType === "opinion_poll").map((p) => p.parentId);

  const [matchupRows, trendingRows, opinionRows] = await Promise.all([
    matchupIds.length > 0
      ? db
          .select({ id: votes.targetId })
          .from(votes)
          .where(
            and(
              eq(votes.userId, userId),
              eq(votes.voteType, "face_off"),
              inArray(votes.targetId, matchupIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
    trendingIds.length > 0
      ? db
          .select({ id: trendingPollVotes.pollId })
          .from(trendingPollVotes)
          .where(
            and(
              eq(trendingPollVotes.userId, userId),
              inArray(trendingPollVotes.pollId, trendingIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
    opinionIds.length > 0
      ? db
          .select({ id: opinionPollVotes.pollId })
          .from(opinionPollVotes)
          .where(
            and(
              eq(opinionPollVotes.userId, userId),
              inArray(opinionPollVotes.pollId, opinionIds),
            ),
          )
      : Promise.resolve([] as Array<{ id: string }>),
  ]);

  const voted = new Set<string>();
  for (const r of matchupRows) voted.add(`matchup:${r.id}`);
  for (const r of trendingRows) voted.add(`trending_poll:${r.id}`);
  for (const r of opinionRows) voted.add(`opinion_poll:${r.id}`);
  return voted;
}

/**
 * Apply the vote-first rule: drop any parent that requires a prior vote
 * if the agent hasn't voted on it yet. Open markets always pass through.
 */
function filterByVoteRequirement(
  parents: EligibleCommentParent[],
  voted: Set<string>,
): EligibleCommentParent[] {
  return parents.filter((parent) => {
    if (!VOTE_REQUIRED_SURFACES.has(parent.parentType)) return true;
    return voted.has(`${parent.parentType}:${parent.parentId}`);
  });
}

async function getEligibleParents(userId: string, allParents?: EligibleCommentParent[]): Promise<EligibleCommentParent[]> {
  const parents = allParents ?? (await getOpenParents());
  if (!parents.length) return [];

  const parentIds = parents.map((parent) => parent.parentId);
  const [existing, voted] = await Promise.all([
    db
      .select({
        parentType: unifiedComments.parentType,
        parentId: unifiedComments.parentId,
      })
      .from(unifiedComments)
      .where(
        and(
          eq(unifiedComments.userId, userId),
          inArray(unifiedComments.parentId, parentIds),
          sql`${unifiedComments.deletedAt} IS NULL`,
        ),
      ),
    getVotedParentKeys(userId, parents),
  ]);
  const alreadyCommented = new Set(existing.map((row) => `${row.parentType}:${row.parentId}`));

  return filterByVoteRequirement(
    parents.filter((parent) => !alreadyCommented.has(`${parent.parentType}:${parent.parentId}`)),
    voted,
  );
}

function chooseParent(parents: EligibleCommentParent[], profile: AgentSimulationProfile): EligibleCommentParent {
  const preferred = parents.filter((parent) => parent.category && profile.favoriteCategories.includes(parent.category));
  const pool = preferred.length > 0 && Math.random() < 0.7 ? preferred : parents;
  return pool[Math.floor(Math.random() * pool.length)];
}

// Templates have been removed in favour of the LLM generator. The previous
// hard-coded pool produced obvious bot-flavoured comments that didn't read
// the actual prompt or vote context — we now pass full surface context to
// the model on every comment.

/** Try to find a parent + reply target for the agent. We pick a small
 *  random sample of open parents and probe each for an eligible target —
 *  no point hammering findReplyTarget on every parent in the universe.
 *  Also enforces the vote-first rule on matchups + polls. */
async function findReplyOpportunity(
  agent: { userId: string; displayName: string },
  allParents: EligibleCommentParent[],
  profile: AgentSimulationProfile,
): Promise<{ parent: EligibleCommentParent; target: ReplyTarget } | null> {
  if (!allParents.length) return null;

  // Vote-first filter — same as top-level path. Replying to a poll you
  // haven't voted on still leaks the bot smell.
  const voted = await getVotedParentKeys(agent.userId, allParents);
  const allowed = filterByVoteRequirement(allParents, voted);
  if (!allowed.length) return null;

  // Bias toward favoured categories first, then everything else.
  const preferred = allowed.filter(
    (p) => p.category && profile.favoriteCategories.includes(p.category),
  );
  const ordered = [...preferred.sort(() => Math.random() - 0.5), ...allowed.sort(() => Math.random() - 0.5)];
  const probed = new Set<string>();

  for (const parent of ordered) {
    const key = `${parent.parentType}:${parent.parentId}`;
    if (probed.has(key)) continue;
    probed.add(key);
    if (probed.size > 6) break;

    const target = await findReplyTarget(parent.parentType, parent.parentId, agent.userId);
    if (target) return { parent, target };
  }
  return null;
}

export async function runCommentSweep(): Promise<{
  posted: number;
  replies: number;
  /** Number of agents that tried the reply path but had no eligible
   *  target and fell back to top-level. Useful for tuning REPLY_PROBABILITY. */
  replyFallbacks: number;
  skipped: number;
  llmRejected: number;
  capReached: boolean;
}> {
  const agents = await db
    .select()
    .from(agentConfigs)
    .where(eq(agentConfigs.isActive, true));

  // Shuffle so the same agents don't always go first and dominate the
  // small daily eligibility pool.
  for (let i = agents.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [agents[i], agents[j]] = [agents[j], agents[i]];
  }

  let posted = 0;
  let replies = 0;
  let replyFallbacks = 0;
  let skipped = 0;
  let llmRejected = 0;
  let capReached = false;

  // One shared parent universe per sweep — cheaper than re-querying for
  // every agent. Each agent then derives their own eligible subset.
  const allParents = await getOpenParents();

  for (const agent of agents) {
    if (posted >= MAX_COMMENTS_PER_SWEEP) {
      capReached = true;
      skipped++;
      continue;
    }

    if (!isV2SimulationProfile(agent.simulationProfile)) {
      skipped++;
      continue;
    }

    const simulation = getSimulationProfile(agent.simulationProfile);
    if (Math.random() > simulation.dailyCommentChance) {
      skipped++;
      continue;
    }

    const weeklyCount = await countAgentCommentsThisWeek(agent.userId);
    if (weeklyCount >= simulation.weeklyCommentCap) {
      skipped++;
      continue;
    }

    let parent: EligibleCommentParent | null = null;
    let replyTarget: ReplyTarget | null = null;
    const wantedReply = Math.random() < REPLY_PROBABILITY;

    // Reply path — try first when the dice say so. If no eligible target
    // exists, fall back to top-level rather than burn the agent's slot.
    if (wantedReply) {
      const opp = await findReplyOpportunity(
        { userId: agent.userId, displayName: agent.displayName },
        allParents,
        simulation,
      );
      if (opp) {
        parent = opp.parent;
        replyTarget = opp.target;
      }
    }

    if (!parent) {
      if (wantedReply) replyFallbacks++;
      const eligible = await getEligibleParents(agent.userId, allParents);
      if (!eligible.length) {
        skipped++;
        continue;
      }
      parent = chooseParent(eligible, simulation);
    }

    const context = await fetchCommentContext(
      parent.parentType,
      parent.parentId,
      agent.userId,
    );
    if (!context) {
      skipped++;
      log(`[CommentWorker] ${agent.displayName}: no context for ${parent.parentType}:${parent.parentId}`);
      continue;
    }

    if (replyTarget) {
      // All four CommentContext variants declare replyTarget?:, so this
      // assignment is type-safe across the union.
      context.replyTarget = replyTarget;
    }

    const agentForComment: AgentForComment = {
      displayName: agent.displayName,
      username: agent.username,
      archetype: agent.archetype,
      bio: agent.bio,
    };

    const body = await generateAgentComment(agentForComment, simulation, context);
    if (!body) {
      llmRejected++;
      skipped++;
      log(`[CommentWorker] ${agent.displayName}: LLM produced no usable comment for ${parent.parentType}${replyTarget ? " (reply)" : ""}`);
      continue;
    }

    try {
      await db.transaction(async (tx) => {
        await tx.insert(unifiedComments).values({
          parentType: parent.parentType,
          parentId: parent.parentId,
          parentCommentId: replyTarget?.commentId ?? null,
          userId: agent.userId,
          body,
        });
        await tx
          .update(profiles)
          .set({ lastActiveAt: new Date() })
          .where(eq(profiles.id, agent.userId));
      });
      posted++;
      if (replyTarget) replies++;
      log(
        `[CommentWorker] ${agent.displayName} ${replyTarget ? `replied to @${replyTarget.authorUsername ?? "user"}` : "commented"} on ${parent.parentType}:${parent.parentId} — "${body.slice(0, 80)}${body.length > 80 ? "…" : ""}"`,
      );
    } catch (err) {
      skipped++;
      log(`[CommentWorker] Failed for ${agent.displayName}: ${err instanceof Error ? err.message : err}`);
    }
  }

  return { posted, replies, replyFallbacks, skipped, llmRejected, capReached };
}

function msUntilNextSweep(): number {
  const now = new Date();
  const tomorrow = new Date(now);
  tomorrow.setUTCDate(now.getUTCDate() + 1);
  tomorrow.setUTCHours(9 + Math.floor(Math.random() * 10), Math.floor(Math.random() * 60), 0, 0);
  return Math.max(60_000, tomorrow.getTime() - now.getTime());
}

function scheduleNextSweep(): void {
  const delay = msUntilNextSweep();
  log(`[CommentWorker] Next sweep in ${(delay / 3_600_000).toFixed(1)}h`);
  setTimeout(async () => {
    try {
      const result = await runCommentSweep();
      log(`[CommentWorker] Sweep complete: ${result.posted} posted (${result.replies} replies), ${result.skipped} skipped`);
    } catch (err) {
      console.error("[CommentWorker] Sweep failed:", err);
    }
    scheduleNextSweep();
  }, delay);
}

export function startCommentWorkerScheduler(): void {
  log(`[CommentWorker] Starting (${COMMENT_WORKER_BOOT_DELAY_MS / 1000}s boot delay, sparse daily sweep)`);
  setTimeout(async () => {
    try {
      const result = await runCommentSweep();
      log(`[CommentWorker] Initial sweep: ${result.posted} posted (${result.replies} replies), ${result.skipped} skipped`);
    } catch (err) {
      console.error("[CommentWorker] Initial sweep failed:", err);
    }
    scheduleNextSweep();
  }, COMMENT_WORKER_BOOT_DELAY_MS);
}
