export { registerCronRoutes } from "./cron-routes";
export { registerPublicRoutes } from "./public-routes";
export { registerGamificationRoutes } from "./gamification-routes";
export { registerFavoritesRoutes } from "./favorites-routes";
export { registerNotificationsRoutes } from "./notifications-routes";
export { registerAdminNotificationsRoutes } from "./admin-notifications-routes";
export { registerOgRoutes } from "./og-routes";
export { registerShareRoutes } from "./share-routes";
export { registerBadgesRoutes } from "./badges-routes";
