-- Phase 10 pre-flight cleanup.
--
-- Purpose: skip any agent actions that were queued before the Phase 0 kill
-- switch was flipped. They were generated by the old hardcoded-parimutuel
-- worker logic and would misfire on the new dual-engine path (e.g. trying
-- to update marketEntries.totalStake on an AMM market whose stake bookkeeping
-- now lives in market_amm_state).
--
-- Run this ONCE against the production DB right BEFORE flipping the agent
-- kill switch back on (after the Phase 10 deploy, before step 9 in the plan).
--
-- Safety: we only target rows older than 1 hour. If you accidentally run
-- this AFTER unpausing the cohort, it won't kill in-flight legitimate
-- actions queued in the last hour. Adjust the interval if your Phase 10
-- deploy was paused for a longer window between deploy and wake.
--
-- Rationale: the worker would already skip these defensively (cutoff /
-- engine mismatch / stale executeAfter), but marking them explicitly keeps
-- the Town Square + admin queues clean and gives us a clear audit trail
-- for "everything from here on was scheduled by Phase 10 code".

-- Dry-run first: how many rows are we about to touch?
SELECT
  COUNT(*) AS stale_pending_count,
  MIN(created_at) AS oldest,
  MAX(created_at) AS newest
FROM scheduled_agent_actions
WHERE status = 'pending'
  AND execute_after <= NOW()
  AND created_at < NOW() - INTERVAL '1 hour';

-- Live update. Keep error_message human-readable so it shows up nicely in
-- the Agent Activity admin tab if anyone audits later.
UPDATE scheduled_agent_actions
SET
  status = 'skipped',
  error_message = 'phase0_stale: queued before agent kill switch, cleared at Phase 10 wake',
  executed_at = NOW()
WHERE status = 'pending'
  AND execute_after <= NOW()
  AND created_at < NOW() - INTERVAL '1 hour';

-- Verify nothing OLD-and-pending remains. (Recent pending actions are NOT
-- counted — those are legitimate post-wake work.)
SELECT COUNT(*) AS still_pending_after_cleanup
FROM scheduled_agent_actions
WHERE status = 'pending'
  AND execute_after <= NOW()
  AND created_at < NOW() - INTERVAL '1 hour';
